BibNumber/BibNumberWeb/Controllers/PhotoAlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhotoProvider;
using System.Diagnostics;
using System.Net.Http;
using System.IO;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Queue;
using System.Configuration;
using Newtonsoft.Json;
using Website;
using Microsoft.AspNet.SignalR;

namespace BibNumberWeb.Controllers
{
    /// <summary>
    /// Provides methods that respond to HTTP requests that are made to the site with url prefix '/PhotoAlbums/'.
    /// </summary>
    public class PhotoAlbumsController : Controller
    {
        private BibNumbersMysqlContext db = new BibNumbersMysqlContext();

        /// <summary>
        /// GET: PhotoAlbums
        /// Load list of albums from a database and navigates to the site where the list is displayed.
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Index()
        {
            return View(await db.PhotoAlbumSet.ToListAsync());
        }

        /// <summary>
        /// GET: PhotoAlbums/Details/5
        /// Loads an album with an specific id and navigates to the site displaying details of the requested album.
        /// </summary>
        /// <param name="id">id of an album to load</param>
        /// <returns>
        /// Bad Request result, if the passed id is null.
        /// Not Found object, if the requested album was not found.
        /// View that is used to render details page, if the requested album was found.
        /// </returns>
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhotoAlbum photoAlbum = await db.PhotoAlbumSet.FindAsync(id);
            if (photoAlbum == null)
            {
                return HttpNotFound();
            }
            return View(photoAlbum);
        }

        /// <summary>
        /// GET: PhotoAlbums/Create
        /// Creates a view that is used to create new album.
        /// </summary>
        /// <returns>View that is used to create new album.</returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// POST: PhotoAlbums/Create
        /// Handles POST request to create new album. Binds Url and Name from the POST data to the photoAlbum parameter.
        /// Checks if the form data are valid and loads photos from the filled url. 
        /// Method is now working only with urls that links to the albums from the rajce.net site.
        /// If the form data are valid, photos from the rajce.net are loaded and new album is created and stored to the database.
        /// After the album is stored to the database, method informs Azure WebJob service to run detection algorithm on the loaded photos.
        /// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        /// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// </summary>
        /// <param name="photoAlbum">album that contains Url and Name passed as POST data</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Url,Name")] PhotoAlbum photoAlbum)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RajcePhotoProvider photoProvider = new RajcePhotoProvider();
                    var photoList = await photoProvider.GetPhotoList(photoAlbum.Url);

                    if (photoList != null
                        && photoList.Count() > 0)
                    {
                        foreach (var photo in photoList)
                        {
                            var photoModel = new Photo()
                            {
                                Url = photo.Url,
                                ThumbnailUrl = photo.ThumbnailUrl
                            };

                            photoAlbum.Photos.Add(photoModel);

                        }
                    }

                    db.PhotoAlbumSet.Add(photoAlbum);
                    await db.SaveChangesAsync();

                    await DetectBibNumbers(photoAlbum);

                    //foreach(var photo in photoAlbum.Photos)
                    //{
                    //    await DetectBibNumbers(photo);
                    //}

                    return Redirect("~/PhotoAlbums/Details/" + photoAlbum.Id);
                }
            }
            catch(Exception ex)
            {

            }
            

            return View(photoAlbum);
        }

        /// <summary>
        /// GET: PhotoAlbums/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhotoAlbum photoAlbum = await db.PhotoAlbumSet.FindAsync(id);
            if (photoAlbum == null)
            {
                return HttpNotFound();
            }
            return View(photoAlbum);
        }

        // POST: PhotoAlbums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Url,Name")] PhotoAlbum photoAlbum)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photoAlbum).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(photoAlbum);
        }

        // GET: PhotoAlbums/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhotoAlbum photoAlbum = await db.PhotoAlbumSet.FindAsync(id);
            if (photoAlbum == null)
            {
                return HttpNotFound();
            }
            return View(photoAlbum);
        }

        // POST: PhotoAlbums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            PhotoAlbum photoAlbum = await db.PhotoAlbumSet.FindAsync(id);
            db.PhotoAlbumSet.Remove(photoAlbum);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Search(int id, FormCollection form)
        {
            var query = form["SearchQuery"];

            if(string.IsNullOrWhiteSpace(query))
            {
                return HttpNotFound();
            }

            int bibNumber = -1;

            if(!int.TryParse(query, out bibNumber))
            {
                return HttpNotFound();
            }

            PhotoAlbum photoAlbum = await db.PhotoAlbumSet.FindAsync(id);

            if (photoAlbum == null)
            {
                return HttpNotFound();
            }

            PhotoAlbum resultsAlbum = new PhotoAlbum();
            var results = photoAlbum.Photos.Where(p => p.BibNumbersAsString.Contains(query)).ToList();
            resultsAlbum.Photos = results;

            TempData["SearchQuery"] = query;
            return View(resultsAlbum);
        }

        public async Task DetectBibNumbers(Photo photo)
        {
            try
            {
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(ConfigurationManager.ConnectionStrings["AzureWebJobsStorage"].ConnectionString);//CloudStorageAccount.Parse("UseDevelopmentStorage=true");
                CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();
                CloudQueue queue = queueClient.GetQueueReference("detectbibnumbersqueue");
                queue.CreateIfNotExists();
                var photoJson = await JsonConvert.SerializeObjectAsync(photo);
                queue.AddMessage(new CloudQueueMessage(photoJson));
            }
            catch (Exception ex)
            {

            }            
        }

        public async Task DetectBibNumbers(PhotoAlbum album)
        {
            try
            {
                var connectionString = ConfigurationManager.ConnectionStrings["AzureWebJobsStorage"].ConnectionString;
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(connectionString);//CloudStorageAccount.Parse("UseDevelopmentStorage=true");tionManager.ConnectionStrings["AzureStorageConnection"].ConnectionString);//CloudStorageAccount.Parse("UseDevelopmentStorage=true");
                CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();
                CloudQueue queue = queueClient.GetQueueReference("detectbibnumbersqueue");
                queue.CreateIfNotExists();
                var albumJson = await JsonConvert.SerializeObjectAsync(album);
                queue.AddMessage(new CloudQueueMessage(albumJson));
            }
            catch (Exception ex)
            {

            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public async Task<ActionResult> ProgressNotification(int jobId, int progress)
        {
            var connections = JobProgressHub.GetUserConnections(jobId);

BibNumber/BibNumberWeb/Views/PhotoAlbums/Create.cshtml
@model BibNumberWeb.PhotoAlbum

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PhotoAlbum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BibNumber/BibNumberWeb/Views/PhotoAlbums/Delete.cshtml
@model BibNumberWeb.PhotoAlbum

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PhotoAlbum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BibNumber/BibNumberWeb/Views/PhotoAlbums/Details.cshtml
@model BibNumberWeb.PhotoAlbum

@{
    ViewBag.Title = "Details";
}

@section CSS
{
    <link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css" />
    @Styles.Render("~/Content/image-gallery-css")
}

@section scripts
{
    <script src="http://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
    @Scripts.Render("~/bundles/image-gallery")
<script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
<script src="~/signalr/hubs"></script>

<script type="text/javascript">
    $(document).ready(function () {
        var jobId = "@Model.Id";

        // Reference the auto-generated proxy for the hub.
        var jobProgressHub = $.connection.jobProgressHub;

        // Create a function that the hub can call back to display progress
        jobProgressHub.client.updateProgress = function (progress) {
            $("#progressbar").width(progress + '%');

            console.log("Progress: " + progress);
        };

        $.connection.hub.logging = true;
        $.connection.hub.qs = "jobId=" + jobId;
        $.connection.hub.start();
    });
</script>

}

<h2>Details</h2>

<form method="post"
      action="@Url.Action("Search", "PhotoAlbums")/@Model.Id/">
    <div>
        <label for="SearchQuery">Search:</label>
        <input type="text" name="SearchQuery" value="" style="color:black"/>
    </div>
</form>



    


        <div class="container">
            <br>
            <div class="progress">
                <div class="progress-bar" id="progressbar" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="100" style="width:@Model.DetectionProgress%">
                </div>
            </div>
            <br>
            <!-- The container for the list of example images -->
            <div id="links">
                @foreach (var photo in Model.Photos)
                {
                    <a href="@photo.Url" title="@photo.BibNumbersAsString" data-gallery="">
                        <img src="@photo.ThumbnailUrl" />
                    </a>
                }
            </div>
            <br>
        </div>
        <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
        <div id="blueimp-gallery" class="blueimp-gallery">
            <!-- The container for the modal slides -->
            <div class="slides"></div>
            <!-- Controls for the borderless lightbox -->
            <h3 class="title"></h3>
            <a class="prev">‹</a>
            <a class="next">›</a>
            <a class="close">×</a>
            <a class="play-pause"></a>
            <ol class="indicator"></ol>
            <!-- The modal dialog, which will be used to wrap the lightbox content -->
            <div class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" aria-hidden="true">&times;</button>
                            <h4 class="modal-title"></h4>
                        </div>
                        <div class="modal-body next"></div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default pull-left prev">
                                <i class="glyphicon glyphicon-chevron-left"></i>
                                Previous
                            </button>
                            <button type="button" class="btn btn-primary next">
                                Next
                                <i class="glyphicon glyphicon-chevron-right"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @*<div>
                <h4>PhotoAlbum</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Url)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Url)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                </dl>
            </div>*@
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

BibNumber/BibNumberWeb/Views/PhotoAlbums/Edit.cshtml
@model BibNumberWeb.PhotoAlbum

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PhotoAlbum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @*<div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BibNumber/BibNumberWeb/Views/PhotoAlbums/Index.cshtml
@model IEnumerable<BibNumberWeb.PhotoAlbum>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

BibNumber/BibNumberWeb/Views/PhotoAlbums/Search.cshtml
@model BibNumberWeb.PhotoAlbum

@{
    ViewBag.Title = "Search";
}

@section CSS
{
    <link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css" />
    @Styles.Render("~/Content/image-gallery-css")
}

@section scripts
{
    <script src="http://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
    @Scripts.Render("~/bundles/image-gallery")
}

<h2>Results</h2>

@*<form method="post"
      action="@Url.Action("Search", "PhotoAlbums")/@Model.Id/">
    <div>
        <label for="SearchQuery">Search:</label>
        <input type="text" name="SearchQuery" value="@TempData["SearchQuery"]"
               style="color:black" />
    </div>
</form>*@

<div class="container">
    <br>
    <!-- The container for the list of example images -->
    <div id="links">
        @foreach (var photo in Model.Photos)
        {
            <a href="@photo.Url" title="@photo.BibNumbersAsString" data-gallery="">
                <img src="@photo.ThumbnailUrl" />
            </a>
        }
    </div>
    <br>
</div>
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>